name: toastification
description: Toastification is a Flutter package that allows you to easily show toast and notification messages in your application.
version: 2.0.0
homepage: https://payamzahedi.com/toastification/
repository: https://github.com/payam-zahedi/toastification
topics: 
  - toast
  - notification
  - message
  - toastification

environment:
  sdk: '>=2.17.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  equatable: ^2.0.5
  uuid: ^4.1.0
  pausable_timer: any
  collection: ^1.16.0
  iconsax_flutter: 
      git:
        url: https://github.com/ahmtydn/iconsax_flutter.git
      
  
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
